version: '3.8'

networks:
  db-net:
    driver: bridge

services:
 mysql:
    image: mysql:8.3.0
    container_name: chat-backend-mysql
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: $DATABASE_PASSWORD
      MYSQL_DATABASE: $DATABASE_NAME
    ports:
      - $DATABASE_PORT:$DATABASE_PORT
    expose:
      - $DATABASE_PORT
    volumes:
      - ./docker/dbdata:/var/lib/mysql/
    networks:
      - db-net